SEGMENTOR_MODEL: fastsam # The segmentor model in ISM (sam , fastsam)
OUTPUT_DIR: /workspace/SAM6D/SAM-6D/Data/linemod-ism-eval-fastsam # Path to root directory of the output
TEMPLATE_DIR: /workspace/SAM6D/SAM-6D/Data/templates
STABILITY_SCORE_THRESH : 0.97 # stability_score_thresh of SAM
DATA_DIR: /workspace/Linemod_preprocessed/data
CAD_DIR: /workspace/Linemod_preprocessed/models
OBJ_ID: [1, 2, 4, 5] # [1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15]